
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_school21_smartcalc_model_SmartCalcNative */

#ifndef _Included_edu_school21_smartcalc_model_SmartCalcNative
#define _Included_edu_school21_smartcalc_model_SmartCalcNative
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     edu_school21_smartcalc_model_SmartCalcNative
 * Method:    calc
 * Signature: (DLjava/lang/String;[D)I
 */
JNIEXPORT jint JNICALL Java_edu_school21_smartcalc_model_SmartCalcNative_calc
  (JNIEnv *, jobject, jdouble, jstring, jdoubleArray);

/*
 * Class:     edu_school21_smartcalc_model_SmartCalcNative
 * Method:    oneOperation
 * Signature: (CD)D
 */
JNIEXPORT jdouble JNICALL Java_edu_school21_smartcalc_model_SmartCalcNative_oneOperation
  (JNIEnv *, jobject, jchar, jdouble);

/*
 * Class:     edu_school21_smartcalc_model_SmartCalcNative
 * Method:    twoOperations
 * Signature: (CDD)D
 */
JNIEXPORT jdouble JNICALL Java_edu_school21_smartcalc_model_SmartCalcNative_twoOperations
  (JNIEnv *, jobject, jchar, jdouble, jdouble);

/*
 * Class:     edu_school21_smartcalc_model_SmartCalcNative
 * Method:    calculateCredit
 * Signature: (DDDI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_edu_school21_smartcalc_model_SmartCalcNative_calculateCredit
  (JNIEnv *, jobject, jdouble, jint, jdouble, jint);

/*
 * Class:     edu_school21_smartcalc_model_SmartCalcNative
 * Method:    calculateDeposit
 * Signature: (DDDDII[DI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_edu_school21_smartcalc_model_SmartCalcNative_calculateDeposit
  (JNIEnv *, jobject, jdouble, jint, jdouble, jdouble, jint, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
